server:
  port: 8080
datasource:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  database: dousheng
  username: root
  password: 123456
  charset: utf8
logger:
  logfilepath: ../log/log.txt
video:
  absolutePath: http://124.222.132.116:8080/home/go/src/dousheng/public/
  savePath: ./public
  maxNumPerTimes: 30