server:
  port: 8080
datasource:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  database: dousheng
  username: root
  password:
  charset: utf8
redis:
  host: 127.0.0.1
  port: 6379
  password:
  db: 0
  poolsize: 100
logger:
  logfilepath: ../log/log.txt
video:
  absolutePath: http://124.222.132.116:8080/home/go/src/dousheng/public/
  savePath: ./public
  maxNumPerTimes: 30
cos:
#  uriPath: https://wuhlan3-1307602190.cos.ap-guangzhou.myqcloud.com/dousheng/
#  url: https://wuhlan3-1307602190.cos.ap-guangzhou.myqcloud.com
  uriVideoPath: https://wuhlan3-1307602190.cos.ap-guangzhou.myqcloud.com/kitexdousheng/video/
  uriPicturePath: https://wuhlan3-1307602190.cos.ap-guangzhou.myqcloud.com/kitexdousheng/img/
  url: https://wuhlan3-1307602190.cos.ap-guangzhou.myqcloud.com
  SecretID:
  SecretKey:
#  videoDir: dousheng/
  videoDir: /kitexdousheng/video/
  imgDir: /kitexdousheng/img/