server:
  port: 8080
datasource:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  database:
  username:
  password:
  charset: utf8
logger:
  logfilepath: ../log/log.txt
video:
  absolutePath:
  savePath: ./public
  maxNumPerTimes: 30
cos:
  uriPath:
  url:
  SecretID:
  SecretKey:
  videoDir:
